from crewai import Agent, Task, Crew, LLM, Process
from dotenv import load_dotenv
import os
import markdown
import uuid
from crew_ba import create_ba_task, business_analyst
from crew_sa import create_sa_task, solution_architect
from crew_ta import create_ta_task, technology_advisor
from crew_dp import create_dp_task, delivery_planner

"""ip_idea = input("Enter your business idea: ")
ip_technology_preference = input("Enter your technology stack preference (enterprise / opensource): ")
ip_daily_traffic = input("Enter an assumption of expected daily traffic: ")
ip_delivery_timeline = input("Enter expected delivery timeline (months): ")
ip_country_of_operation = input("Enter country where data will be hosted: ")"""

def generate_solution(
    business_idea,
    technology_preference,
    cloud_preference,
    daily_traffic,
    delivery_timeline_months,
    country
):
    my_uuid = uuid.uuid4()

    ba_task = create_ba_task(
        business_idea,
        technology_preference,
        cloud_preference,
        daily_traffic,
        delivery_timeline_months,
        country
    )

    sa_task = create_sa_task(ba_task)
    ta_task = create_ta_task(ba_task, sa_task)
    dp_task = create_dp_task(ba_task, sa_task, ta_task)

    crew = Crew(
        agents=[business_analyst, solution_architect, technology_advisor, delivery_planner],
        tasks=[ba_task, sa_task, ta_task, dp_task],
        process=Process.sequential,
        verbose=True
    )

    result = crew.kickoff()

    print(result)

    html_body = markdown.markdown(
    str(result),
    extensions=["tables", "fenced_code"]
)

    html_document = f"""
    <!DOCTYPE html>
    <html lang="en">

    <head>

    <meta charset="UTF-8">

    <meta name="viewport"
        content="width=device-width, initial-scale=1.0">

    <title>AI Solution Blueprint</title>

    <style>

    * {{
        box-sizing: border-box;
    }}

    body {{
        margin: 0;
        padding: 40px;

        font-family:
            -apple-system,
            BlinkMacSystemFont,
            "Segoe UI",
            Roboto,
            Arial,
            sans-serif;

        background: #f4f7fb;
        color: #1f2937;

        line-height: 1.65;
    }}

    .container {{
        max-width: 1200px;
        margin: auto;
    }}

    header {{
        background: linear-gradient(
            135deg,
            #1e3a8a,
            #4f46e5
        );

        color: white;

        padding: 45px 50px;

        border-radius: 18px;

        margin-bottom: 30px;

        box-shadow:
            0 10px 30px rgba(0,0,0,0.12);
    }}

    header h1 {{
        margin: 0 0 10px 0;
        font-size: 34px;
    }}

    header p {{
        margin: 0;
        opacity: 0.9;
        font-size: 16px;
    }}

    h1 {{
        color: #111827;
    }}

    h2 {{
        margin-top: 45px;

        color: #1e3a8a;

        border-bottom: 2px solid #e5e7eb;

        padding-bottom: 10px;
    }}

    h3 {{
        color: #4338ca;
        margin-top: 30px;
    }}

    table {{
        width: 100%;

        border-collapse: collapse;

        margin: 20px 0;

        background: white;

        border-radius: 10px;

        overflow: hidden;

        box-shadow:
            0 3px 12px rgba(0,0,0,0.06);
    }}

    th {{
        background: #eef2ff;

        color: #312e81;

        font-weight: 600;
    }}

    th, td {{
        padding: 13px 15px;

        border-bottom: 1px solid #e5e7eb;

        text-align: left;
    }}

    tr:last-child td {{
        border-bottom: none;
    }}

    blockquote {{
        margin: 25px 0;

        padding: 18px 22px;

        background: #eef2ff;

        border-left: 5px solid #4f46e5;

        border-radius: 8px;
    }}

    code {{
        background: #eef2f7;

        padding: 3px 6px;

        border-radius: 5px;

        font-size: 0.9em;
    }}

    pre {{
        background: #111827;

        color: #e5e7eb;

        padding: 20px;

        border-radius: 10px;

        overflow-x: auto;
    }}

    pre code {{
    background: transparent;
    color: #e5e7eb;
    padding: 0;
    border-radius: 0;
    font-size: 14px;
    }}

    ul, ol {{
        padding-left: 25px;
    }}

    li {{
        margin-bottom: 6px;
    }}

    strong {{
        color: #111827;
    }}

    .footer {{
        margin-top: 50px;

        padding: 20px;

        text-align: center;

        color: #6b7280;

        font-size: 13px;
    }}

    </style>

    </head>

    <body>

    <div class="container">

    <header>

        <h1>🤖 AI Solution Blueprint</h1>

        <p>
            Generated by the AI Solution Consultant
        </p>

    </header>

    {html_body}

    <div class="footer">

        Generated by AI Solution Consultant

    </div>

    </div>

    </body>

    </html>
    """

    os.makedirs("output", exist_ok=True)
    output_file = os.path.join("output", f"{my_uuid}_solution_blueprint.html")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write(html_document)

    print(f"HTML report saved to: {output_file}")

    return {
    "result": str(result),
    "html": html_document,
    "output_file": output_file
    }